server:
  port: 9001
#设置redis服务器的host或者ip地址，其他参数的注释详情见RedisConfig.java文件
universe:
  redis:
    hostName: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    pool.maxTotal: 4
    pool.maxIdle: 4
    pool.minIdle: 1
    pool.blockWhenExhausted: true
    pool.maxWaitMillis: 60000
    pool.testOnBorrow: false
    pool.testOnReturn: false
    pool.jmxEnabled: true
    pool.testWhileIdle: true
    pool.timeBetweenEvictionRunsMillis: 60000
    pool.minEvictableIdleTimeMillis: 120000
    pool.numTestsPerEvictionRun: 1
