CREATE TABLE `weather_data` (
`id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
`time` datetime NOT NULL COMMENT '数据时间点',
`city_no` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '地市编码',
`city_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '地市名称',
`load_mw` decimal(10,2) DEFAULT NULL COMMENT '电力负荷(MW)',
`temp` decimal(5,1) DEFAULT NULL COMMENT '温度(℃)',
`humidity` int DEFAULT NULL COMMENT '相对湿度(%)',
`weather_code` tinyint DEFAULT NULL COMMENT '天气编码 0晴1多云2阴3小雨4中雨5霾6浮尘',
`is_rain` tinyint DEFAULT NULL COMMENT '是否降雨 0否1是',
`hour` tinyint DEFAULT NULL COMMENT '小时 0-23',
`day_of_week` tinyint DEFAULT NULL COMMENT '星期1-7',
`is_holiday` tinyint DEFAULT NULL COMMENT '是否节假日 0否1是',
`shortwave_radiation` decimal(8,2) DEFAULT NULL COMMENT '总短波辐射(W/m²)',
`direct_radiation` decimal(8,2) DEFAULT NULL COMMENT '直接辐射(W/m²)',
`diffuse_radiation` decimal(8,2) DEFAULT NULL COMMENT '散射辐射(W/m²)',
`sunshine_duration` int DEFAULT NULL COMMENT '日照时长(秒/小时)',
`wind_level` tinyint DEFAULT NULL COMMENT '风力等级(0-12级)',
`wind_direction` decimal(6,2) DEFAULT NULL COMMENT '风向(°)',
`wind_gusts` decimal(5,1) DEFAULT NULL COMMENT '阵风风速(m/s)',
`wind_speed` decimal(4,1) DEFAULT NULL COMMENT '风速(km/h)',
`create_time` datetime DEFAULT NULL COMMENT '创建时间',
PRIMARY KEY (`id`),
UNIQUE KEY `uk_time_city_no` (`time`,`city_no`) USING BTREE,
KEY `idx_city_time` (`city_no`,`time`)
) ENGINE=InnoDB AUTO_INCREMENT=4441 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='气温数据小时级';

CREATE TABLE `weather_data_hour` (
 `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
 `time` datetime NOT NULL COMMENT '数据时间点',
 `city_no` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '地市编码',
 `city_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '地市名称',
 `load_mw` decimal(10,2) DEFAULT NULL COMMENT '电力负荷(MW)',
 `temp` decimal(5,1) DEFAULT NULL COMMENT '温度(℃)',
 `humidity` int DEFAULT NULL COMMENT '相对湿度(%)',
 `weather_code` tinyint DEFAULT NULL COMMENT '天气编码 0晴1多云2阴3小雨4中雨5霾6浮尘',
 `is_rain` tinyint DEFAULT NULL COMMENT '是否降雨 0否1是',
 `hour` tinyint DEFAULT NULL COMMENT '小时 0-23',
 `day_of_week` tinyint DEFAULT NULL COMMENT '星期1-7',
 `is_holiday` tinyint DEFAULT NULL COMMENT '是否节假日 0否1是',
 `shortwave_radiation` decimal(8,2) DEFAULT NULL COMMENT '总短波辐射(W/m²)',
 `direct_radiation` decimal(8,2) DEFAULT NULL COMMENT '直接辐射(W/m²)',
 `diffuse_radiation` decimal(8,2) DEFAULT NULL COMMENT '散射辐射(W/m²)',
 `sunshine_duration` int DEFAULT NULL COMMENT '日照时长(秒/小时)',
 `wind_level` tinyint DEFAULT NULL COMMENT '风力等级(0-12级)',
 `wind_direction` decimal(6,2) DEFAULT NULL COMMENT '风向(°)',
 `wind_gusts` decimal(5,1) DEFAULT NULL COMMENT '阵风风速(m/s)',
 `wind_speed` decimal(4,1) DEFAULT NULL COMMENT '风速(km/h)',
 `create_time` datetime DEFAULT NULL COMMENT '创建时间',
 PRIMARY KEY (`id`),
 UNIQUE KEY `uk_time_city_no` (`time`,`city_no`) USING BTREE,
 KEY `idx_city_time` (`city_no`,`time`)
) ENGINE=InnoDB AUTO_INCREMENT=292208 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='气温数据小时级';

